import { mkdir, copyFile, cp, rm } from 'node:fs/promises';
import path from 'node:path';
const target=path.resolve('dist');
if(path.dirname(target)!==process.cwd() || path.basename(target)!=='dist') throw new Error('Unsafe output directory');
await rm(target,{recursive:true,force:true});
await mkdir('dist',{recursive:true});
await copyFile('index.html','dist/index.html');
await cp('src','dist/src',{recursive:true});
await cp('stages','dist/stages',{recursive:true});
await copyFile('sunrise_at_pixel_peak.mp3','dist/sunrise_at_pixel_peak.mp3');
console.log('Built dist/');
