import { TILE, PARTS, StageEditor, StageStore, createStage, validateStage, defaultPropsFor } from './stage.js';
import { GameEngine } from './engine.js';
import { render } from './render.js';
import { encodeStage, decodeStage } from './share.js';
import { BACKGROUNDS } from './backgrounds.js';
const app=document.querySelector('#app'),store=new StageStore();
let sampleStage=createStage();
try { const response=await fetch('./stages/sample.json'); if(response.ok) sampleStage=validateStage(await response.json()); } catch { /* The blank stage remains available if the sample cannot be loaded. */ }
let editor=null,id=null,mode='home',tool='block',camera=0,editCamera=0,game=null,canvas,ctx,scale=1,w=1,h=1,selected=null,cameraY=0,editCameraY=0,frame=0,dirty=false;
let cleanup=()=>{}, last=0,accumulator=0,clearShown=false;
const input={left:false,right:false,jump:false,jumpHeld:false}, keys=new Set(), touches=new Map();
const isPortrait=()=>matchMedia('(orientation: portrait)').matches;
const isCoarse=()=>matchMedia('(pointer: coarse)').matches;
const playSafeBottom=()=>isPortrait()?Math.min(150,Math.max(104,h*.22)):20;
const escapeHTML=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',2600);}
function safely(fn){try{return fn();}catch(e){toast(`操作できませんでした：${e.message}`);return null;}}
function stop(){cancelAnimationFrame(frame);cleanup();cleanup=()=>{};keys.clear();touches.clear();input.left=input.right=input.jump=input.jumpHeld=false;}
function confirmAction(title,text,action){const layer=document.createElement('div');layer.className='overlay';layer.style.position='fixed';layer.style.zIndex='30';layer.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-label="${title}"><h2>${title}</h2><p>${text}</p><div class="actions"><button data-cancel>キャンセル</button><button class="primary" data-ok>続ける</button></div></div>`;app.append(layer);layer.querySelector('[data-cancel]').onclick=()=>layer.remove();layer.querySelector('[data-ok]').onclick=()=>{layer.remove();action();};layer.querySelector('[data-cancel]').focus();}
function shareStage(stage){const code=safely(()=>encodeStage(stage));if(!code)return;const layer=document.createElement('div');layer.className='overlay';layer.style.position='fixed';layer.style.zIndex='35';layer.innerHTML=`<div class="modal share-modal" role="dialog" aria-modal="true" aria-label="ステージを共有"><span class="tag">STAGE CODE</span><h2>ステージを共有</h2><p>このコードを送れば、別の端末でも同じステージを読み込めます。</p><textarea class="share-code" readonly></textarea><div class="actions"><button data-close>閉じる</button><button class="primary" data-copy>コードをコピー</button></div></div>`;app.append(layer);const area=layer.querySelector('textarea');area.value=code;layer.querySelector('[data-close]').onclick=()=>layer.remove();layer.querySelector('[data-copy]').onclick=async()=>{let copied=false;try{await navigator.clipboard.writeText(code);copied=true;}catch{area.focus();area.select();copied=document.execCommand?.('copy')??false;}toast(copied?'共有コードをコピーしました':'コードを選択してコピーしてください');};}
function importStage(){const layer=document.createElement('div');layer.className='overlay';layer.style.position='fixed';layer.style.zIndex='35';layer.innerHTML='<div class="modal share-modal" role="dialog" aria-modal="true" aria-label="共有コードを読み込む"><span class="tag">IMPORT</span><h2>共有コードを読み込む</h2><p>JO1. から始まるコードを貼り付けてください。</p><textarea class="share-code" placeholder="JO1. ..."></textarea><div class="actions"><button data-cancel>キャンセル</button><button class="primary" data-import>読み込む</button></div></div>';app.append(layer);const area=layer.querySelector('textarea');layer.querySelector('[data-cancel]').onclick=()=>layer.remove();layer.querySelector('[data-import]').onclick=()=>{const stage=safely(()=>decodeStage(area.value));if(!stage)return;const imported={...stage,name:(stage.name+'・共有').slice(0,60)};const saved=safely(()=>store.save(imported));if(!saved)return;layer.remove();home();toast('共有ステージを追加しました');};area.focus();}
function stageSettings(){const layer=document.createElement('div');layer.className='overlay';layer.style.position='fixed';layer.style.zIndex='35';layer.innerHTML=`<div class="modal settings-modal" role="dialog" aria-modal="true" aria-label="ステージ背景"><span class="tag">WORLD</span><h2>ステージ背景</h2><label class="field"><span>背景</span><select id="background">${Object.values(BACKGROUNDS).map(bg=>`<option value="${bg.id}">${bg.name}</option>`).join('')}</select></label><p>プレイ画面と編集画面の世界観を、このステージだけ変更できます。</p><div class="actions"><button data-cancel>キャンセル</button><button class="primary" data-apply>変更</button></div></div>`;app.append(layer);const select=layer.querySelector('#background');select.value=editor.stage.background??'tropicalSea';layer.querySelector('[data-cancel]').onclick=()=>layer.remove();layer.querySelector('[data-apply]').onclick=()=>{editor.change(s=>s.background=select.value);dirty=true;layer.remove();refresh();toast('背景を変更しました');};}

function partSettings(x,y){const object=editor.stage.objects.find(o=>o.x===x&&o.y===y);if(!object){toast('調整したいパーツをタップしてください');return;}const configurable=['cannon','movingPlatform','timerSwitch','warp'];if(!configurable.includes(object.type)){toast('このパーツには個別設定がありません');return;}const current={...defaultPropsFor(object.type),...(object.props??{})};let fields='';if(object.type==='cannon')fields=`<label class="field"><span>向き</span><select name="direction"><option value="right">右</option><option value="left">左</option></select></label><label class="field"><span>発射間隔（秒）</span><input name="interval" type="number" min=".3" max="8" step=".1" value="${current.interval}"></label>`;if(object.type==='movingPlatform')fields=`<label class="field"><span>移動方向</span><select name="axis"><option value="x">左右</option><option value="y">上下</option></select></label><label class="field"><span>移動距離（マス）</span><input name="distance" type="number" min=".5" max="12" step=".5" value="${current.distance}"></label><label class="field"><span>速度</span><input name="speed" type="number" min=".2" max="4" step=".05" value="${current.speed}"></label>`;if(object.type==='timerSwitch')fields=`<label class="field"><span>有効時間（秒）</span><input name="duration" type="number" min=".5" max="15" step=".1" value="${current.duration}"></label>`;if(object.type==='warp'){const others=editor.stage.objects.filter(o=>o.type==='warp'&&(o.x!==x||o.y!==y));fields=`<label class="field"><span>接続先</span><select name="target"><option value="">次に置かれたワープ</option>${others.map(o=>`<option value="${o.x},${o.y}">ワープ ${o.x}, ${o.y}</option>`).join('')}</select></label>`;}const layer=document.createElement('div');layer.className='overlay';layer.style.position='fixed';layer.style.zIndex='35';layer.innerHTML=`<div class="modal settings-modal" role="dialog" aria-modal="true" aria-label="パーツ設定"><span class="tag">PART SETTINGS</span><h2>${PARTS[object.type][1]}</h2><div class="settings-form">${fields}</div><div class="actions"><button data-cancel>キャンセル</button><button class="primary" data-apply>反映</button></div></div>`;app.append(layer);const form=layer.querySelector('.settings-form');for(const [key,value] of Object.entries(current)){const el=form.querySelector(`[name="${key}"]`);if(el)el.value=String(value);}layer.querySelector('[data-cancel]').onclick=()=>layer.remove();layer.querySelector('[data-apply]').onclick=()=>{const props={...current};for(const el of form.querySelectorAll('[name]'))props[el.name]=el.type==='number'?Number(el.value):el.value;const candidate=structuredClone(editor.stage);candidate.objects.find(o=>o.x===x&&o.y===y).props=props;if(!safely(()=>validateStage(candidate)))return;editor.change(s=>{s.objects.find(o=>o.x===x&&o.y===y).props=props;});dirty=true;layer.remove();refresh();toast('パーツ設定を反映しました');};}

function home(){stop();mode='home';app.innerHTML=`<main class="page"><header class="top"><div class="brand">◈ ジョーメーカー<small>BUILD YOUR LITTLE ADVENTURE</small></div><span class="tag">つくる。あそぶ。もう一度。</span></header><section class="hero"><div><span class="tag">YOUR WORLD, YOUR RULES</span><h1>ひとつ置いたら、<br><em>冒険がはじまる。</em></h1><p>足場をならべて、コインをひとつ。<br>指でつくった世界へ、そのまま飛びこもう。</p><div class="actions"><button class="primary" id="new">＋ ステージをつくる</button><button id="sample">▷ おためしプレイ</button><button id="import">⇩ 共有コード</button></div></div><div class="hero-art"><span class="art-label">✦ アイデアを、冒険に。</span><canvas id="art" width="600" height="370"></canvas></div></section><section><div class="section-title"><h2>あなたのステージ</h2><span class="tag">MY STAGES</span></div><div class="cards" id="cards"></div></section><p class="footer">このブラウザーに保存されます · タッチ／キーボード対応 · オリジナルの小さな世界</p></main>`;
  const art=app.querySelector('#art');const sample=structuredClone(sampleStage);const preview=new GameEngine(sample);preview.player.x=160;preview.player.y=510;render(art.getContext('2d'),600,370,sample,0,.55,false,preview,0);
  app.querySelector('#new').onclick=()=>openEditor(createStage());app.querySelector('#sample').onclick=()=>{openEditor(sample);play();};app.querySelector('#import').onclick=importStage;
  const rows=safely(()=>store.list()),cards=app.querySelector('#cards');if(!rows){cards.innerHTML='<div class="empty">保存データを読み込めませんでした。ブラウザーの保存設定を確認してください。</div>';return;}if(!rows.length)cards.innerHTML='<div class="empty">まだ、まっさらな世界。<br><br>最初のステージをつくってみよう。</div>';
  for(const row of rows){const card=document.createElement('article');card.className='card';card.innerHTML=`<canvas width="500" height="110"></canvas><h3>${escapeHTML(row.name)}</h3><p>${new Date(row.updatedAt).toLocaleDateString('ja-JP')} 更新 · ${row.data.width} マス</p><div class="actions"><button class="primary" data-play>▷ 遊ぶ</button><button data-edit>編集</button><button data-share>共有</button><button data-copy aria-label="ステージを複製">複製</button><button data-delete class="quiet danger">削除</button></div>`;cards.append(card);render(card.querySelector('canvas').getContext('2d'),500,110,row.data,0,110/(row.data.height*TILE),false,null,0);card.querySelector('[data-edit]').onclick=()=>openEditor(row.data,row.id);card.querySelector('[data-play]').onclick=()=>{openEditor(row.data,row.id);play();};card.querySelector('[data-share]').onclick=()=>shareStage(row.data);card.querySelector('[data-copy]').onclick=()=>{if(safely(()=>store.save({...row.data,name:(row.name+' のコピー').slice(0,60)})))home();};card.querySelector('[data-delete]').onclick=()=>confirmAction('ステージを削除',`「${escapeHTML(row.name)}」を削除します。元に戻せません。`,()=>{safely(()=>{store.remove(row.id);home();});});}
}
function openEditor(stage,stageId=null){editor=new StageEditor(stage);id=stageId;camera=0;editCamera=0;editCameraY=null;dirty=false;tool='block';showEditor();}
function showEditor(){stop();mode='edit';game=null;camera=editCamera;cameraY=editCameraY;app.innerHTML=`<main class="workspace"><header class="toolbar"><button id="back" aria-label="ステージ一覧へ">⌂ 一覧</button><span class="mode">CREATE</span><input id="name" aria-label="ステージ名" maxlength="60"><button id="undo" aria-label="元に戻す">↶</button><button id="redo" aria-label="やり直す">↷</button><button id="save">保存</button><button id="world">背景</button><button id="share">共有</button><button id="play" class="accent">▷ プレイ</button></header><div class="viewport"><canvas aria-label="ステージ編集エリア"></canvas><div class="hint" id="hint"></div></div><nav class="palette" aria-label="パーツパレット">${Object.entries(PARTS).map(([key,[icon,label]])=>`<button data-tool="${key}" aria-pressed="false"><b>${icon}</b>${label}</button>`).join('')}<button data-tool="erase"><b>⌫</b>消しゴム</button><button data-tool="pan"><b>✥</b>移動</button><button data-tool="configure"><b>⚙</b>調整</button><button id="reset" class="danger"><b>↺</b>初期化</button></nav><div class="editor-bottom"><span id="position">位置 0</span><input id="scroll" aria-label="ステージの横位置" type="range" min="0" value="0"><span>${editor.stage.width} マス</span></div></main>`;
  const name=app.querySelector('#name');name.value=editor.stage.name;name.onchange=()=>{editor.change(s=>s.name=name.value.trim()||'名前のない冒険');dirty=true;refresh();};app.querySelector('#back').onclick=()=>dirty?confirmAction('一覧に戻る','未保存の変更があります。保存せずに戻りますか？',home):home();app.querySelector('#save').onclick=()=>{const result=safely(()=>store.save(editor.stage,id));if(result){id=result;dirty=false;toast('ステージを保存しました');}};app.querySelector('#world').onclick=stageSettings;app.querySelector('#share').onclick=()=>shareStage(editor.stage);app.querySelector('#play').onclick=play;
  app.querySelector('#undo').onclick=()=>{editor.undo();dirty=true;refresh();};app.querySelector('#redo').onclick=()=>{editor.redo();dirty=true;refresh();};app.querySelector('#reset').onclick=()=>confirmAction('ステージを初期化','配置を最初の状態に戻します。Undoで取り消せます。',()=>{editor.change(s=>{const fresh=createStage();s.objects=fresh.objects;s.playerStart=fresh.playerStart;});dirty=true;refresh();});
  for(const button of app.querySelectorAll('[data-tool]'))button.onclick=()=>{tool=button.dataset.tool;refresh();};app.querySelector('#scroll').oninput=e=>{camera=Number(e.target.value);editCamera=camera;};setupCanvas();
  let pointer=null,lastPaint=null;const point=e=>{const rect=canvas.getBoundingClientRect();return{x:(e.clientX-rect.left)/scale+camera,y:(e.clientY-rect.top)/scale+cameraY};};
  const paint=e=>{const p=point(e),x=Math.floor(p.x/TILE),y=Math.floor(p.y/TILE),key=`${x},${y}`;selected={x,y};if(key===lastPaint)return;lastPaint=key;if(editor.strokePlace(tool,x,y))dirty=true;refresh();};
  canvas.onpointerdown=e=>{e.preventDefault();if(pointer!==null)return;if(tool==='configure'){const p=point(e),x=Math.floor(p.x/TILE),y=Math.floor(p.y/TILE);selected={x,y};partSettings(x,y);return;}pointer={id:e.pointerId,x:e.clientX,y:e.clientY,camera,cameraY};canvas.setPointerCapture(e.pointerId);if(tool!=='pan'){editor.beginStroke();lastPaint=null;paint(e);}};
  canvas.onpointermove=e=>{if(!pointer||pointer.id!==e.pointerId)return;if(tool==='pan'){camera=Math.max(0,Math.min(maxCamera(),pointer.camera-(e.clientX-pointer.x)/scale));editCamera=camera;cameraY=Math.max(0,Math.min(editor.stage.height*TILE-h/scale,pointer.cameraY-(e.clientY-pointer.y)/scale));editCameraY=cameraY;}else if(['start','goal'].includes(tool)){const p=point(e);selected={x:Math.floor(p.x/TILE),y:Math.floor(p.y/TILE)};}else paint(e);};
  const finishPointer=e=>{if(!pointer||pointer.id!==e.pointerId)return;if(tool!=='pan'){if(editor.endStroke())dirty=true;refresh();}pointer=null;lastPaint=null;selected=null;};
  canvas.onpointerup=finishPointer;canvas.onpointercancel=finishPointer;refresh();run();
}
function refresh(){if(mode!=='edit')return;app.querySelector('#name').value=editor.stage.name;app.querySelector('#undo').disabled=!editor.undoStack.length;app.querySelector('#redo').disabled=!editor.redoStack.length;for(const b of app.querySelectorAll('[data-tool]')){b.classList.toggle('selected',b.dataset.tool===tool);b.setAttribute('aria-pressed',String(b.dataset.tool===tool));}app.querySelector('#hint').textContent=tool==='pan'?'✥ ドラッグしてステージを移動':tool==='erase'?'⌫ タップ／ドラッグでパーツを消去':tool==='configure'?'⚙ 設定したいパーツをタップ':`${PARTS[tool][1]} · タップ／ドラッグで配置` ;}
function maxCamera(){return Math.max(0,editor.stage.width*TILE-w/scale);}
function setupCanvas(){canvas=app.querySelector('.viewport canvas');ctx=canvas.getContext('2d');const resize=()=>{const r=canvas.parentElement.getBoundingClientRect();w=r.width;h=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);scale=Math.max(.75,h/(editor.stage.height*TILE));cameraY=Math.max(0,Math.min(cameraY??Infinity,editor.stage.height*TILE-h/scale));camera=Math.max(0,Math.min(camera,maxCamera()));};const observer=new ResizeObserver(resize);observer.observe(canvas.parentElement);resize();cleanup=()=>observer.disconnect();}
function play(){if(!editor.stage.objects.some(o=>o.type==='goal')){toast('ゴールを置いてからプレイしましょう');return;}editCamera=camera;editCameraY=cameraY;stop();mode='play';game=new GameEngine(editor.stage);clearShown=false;const playHint=isCoarse()?'左右で移動　ジャンプは長押しで高く跳べる':'A・D / ← → 移動　ジャンプは押す長さで高さが変化';app.innerHTML=`<main class="workspace playing"><header class="toolbar"><button id="edit">← 編集に戻る</button><span class="mode">PLAY</span><strong>${escapeHTML(editor.stage.name)}</strong><span class="spacer"></span><button id="restart">↺ リトライ</button></header><div class="viewport"><canvas aria-label="ゲーム画面"></canvas><div class="play-top-ui"><div class="hud" id="hud"></div><div class="hint">${playHint}</div><div class="portrait">横向きにすると、広く見渡せます ↻</div></div><div class="controls"><div class="move"><button data-input="left" aria-label="左へ移動">◀</button><button data-input="right" aria-label="右へ移動">▶</button></div><button class="jump" data-input="jump" aria-label="ジャンプ">ジャンプ</button></div></div></main>`;app.querySelector('#edit').onclick=showEditor;app.querySelector('#restart').onclick=()=>{game.reset();clearShown=false;app.querySelector('.overlay')?.remove();};setupCanvas();
  const controlButtons=[...app.querySelectorAll('[data-input]')];
  const sync=()=>{const active=[...touches.values()];input.left=keys.has('ArrowLeft')||keys.has('KeyA')||active.includes('left');input.right=keys.has('ArrowRight')||keys.has('KeyD')||active.includes('right');input.jumpHeld=keys.has('ArrowUp')||keys.has('KeyW')||keys.has('Space')||active.includes('jump');for(const b of controlButtons)b.classList.toggle('pressed',active.includes(b.dataset.input));};
  const releasePointer=pointerId=>{if(!touches.has(pointerId))return;touches.delete(pointerId);sync();};
  for(const b of controlButtons){b.oncontextmenu=e=>e.preventDefault();b.ondragstart=e=>e.preventDefault();b.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();releasePointer(e.pointerId);touches.set(e.pointerId,b.dataset.input);try{b.setPointerCapture(e.pointerId);}catch{}if(b.dataset.input==='jump')input.jump=true;sync();};b.onpointermove=e=>{if(!touches.has(e.pointerId))return;const r=b.getBoundingClientRect(),pad=14;if(e.clientX<r.left-pad||e.clientX>r.right+pad||e.clientY<r.top-pad||e.clientY>r.bottom+pad){releasePointer(e.pointerId);try{if(b.hasPointerCapture(e.pointerId))b.releasePointerCapture(e.pointerId);}catch{}}};b.onpointerup=e=>releasePointer(e.pointerId);b.onpointercancel=e=>releasePointer(e.pointerId);b.onlostpointercapture=e=>releasePointer(e.pointerId);}
  const endPointer=e=>releasePointer(e.pointerId);
  const allowed=['ArrowLeft','ArrowRight','ArrowUp','KeyA','KeyD','KeyW','Space'];const down=e=>{if(!allowed.includes(e.code))return;e.preventDefault();if(!e.repeat&&['ArrowUp','KeyW','Space'].includes(e.code))input.jump=true;keys.add(e.code);sync();};const up=e=>{keys.delete(e.code);sync();};const blur=()=>{keys.clear();touches.clear();input.jump=input.jumpHeld=false;sync();last=0;accumulator=0;};const visibility=()=>{if(document.hidden)blur();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('pointerup',endPointer,true);window.addEventListener('pointercancel',endPointer,true);window.addEventListener('blur',blur);window.addEventListener('pagehide',blur);window.addEventListener('orientationchange',blur);document.addEventListener('visibilitychange',visibility);const previous=cleanup;cleanup=()=>{previous();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('pointerup',endPointer,true);window.removeEventListener('pointercancel',endPointer,true);window.removeEventListener('blur',blur);window.removeEventListener('pagehide',blur);window.removeEventListener('orientationchange',blur);document.removeEventListener('visibilitychange',visibility);};run();
}
function run(){last=0;accumulator=0;const tick=now=>{const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(mode==='play'){accumulator+=dt;while(accumulator>=1/120){game.step(1/120,input);input.jump=false;accumulator-=1/120;}camera=Math.max(0,Math.min(maxCamera(),game.player.x-w/scale*.4));const safeBottom=playSafeBottom()/scale;const maxPlayCameraY=Math.max(0,editor.stage.height*TILE-h/scale+safeBottom);cameraY=Math.max(0,Math.min(maxPlayCameraY,game.player.y-(h-playSafeBottom())/scale*.58));app.querySelector('#hud').textContent=`● ${game.coins.size}/${editor.stage.objects.filter(o=>o.type==='coin').length}　⚿ ${game.keys}　${game.switchOn?'ON':'OFF'}${editor.stage.objects.some(o=>o.type==='timerSwitch')?`　◷ ${game.timerGate.toFixed(1)}`:''}${editor.stage.objects.some(o=>o.type==='enemyDoor')?`　◆ ${game.enemies.length}`:''}　↺ ${game.deaths}`;if(game.clear&&!clearShown){clearShown=true;const layer=document.createElement('div');layer.className='overlay';layer.innerHTML='<div class="modal"><span class="tag">NICE ADVENTURE!</span><h2>STAGE CLEAR ✦</h2><p>あなたの世界を、駆けぬけた。</p><div class="actions"><button id="again" class="accent">もう一度</button><button id="return" class="primary">編集に戻る</button><button id="list">一覧へ</button></div></div>';canvas.parentElement.append(layer);layer.querySelector('#again').onclick=()=>{layer.remove();game.reset();clearShown=false;};layer.querySelector('#return').onclick=showEditor;layer.querySelector('#list').onclick=()=>dirty?confirmAction('一覧に戻る','未保存の変更があります。保存せずに戻りますか？',home):home();}}
    render(ctx,w,h,editor.stage,camera,scale,mode==='edit',game,now/1000,selected,cameraY);if(mode==='edit'){const slider=app.querySelector('#scroll');slider.max=maxCamera();slider.value=camera;app.querySelector('#position').textContent=`位置 ${Math.floor(camera/TILE)}`;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
home();
